version: 1
update_configs:
  - directory: /
    package_manager: javascript
    update_schedule: live
    target_branch: develop
    automerged_updates:
      - match:
          dependency_type: development
          update_type: all
      - match:
          dependency_type: production
          update_type: semver:minor
    commit_message:
      prefix: 'chore'
      include_scope: false
